[package]
name = "gateman"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
clap = { version = "3", features = ["derive"]}

[dependencies]


[dependencies.rppal]
version = "0.13"
features = ["hal"]

